# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtJKTLe9bwJXykOzlL_pAor0c7zF-Tts
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

st.set_page_config(page_title="K-Means Clustering", layout="wide")

st.title("📊 K-Means Clustering Demo")

uploaded_file = st.file_uploader(
    "Upload income.csv",
    type=["csv"]
)

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.subheader("Dataset")
    st.dataframe(df)

    st.subheader("Original Data")

    fig, ax = plt.subplots()
    ax.scatter(df["Age"], df["Income($)"])
    ax.set_xlabel("Age")
    ax.set_ylabel("Income ($)")
    st.pyplot(fig)

    st.sidebar.header("Model Settings")

    n_clusters = st.sidebar.slider(
        "Number of Clusters",
        min_value=2,
        max_value=10,
        value=3
    )

    scale_data = st.sidebar.checkbox(
        "Scale Data (Recommended)",
        value=True
    )

    data = df[["Age", "Income($)"]].copy()

    if scale_data:
        scaler = MinMaxScaler()
        data = scaler.fit_transform(data)

    km = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10
    )

    clusters = km.fit_predict(data)

    df["Cluster"] = clusters

    st.subheader("Clustered Data")

    fig2, ax2 = plt.subplots()

    for cluster in range(n_clusters):
        cluster_data = df[df["Cluster"] == cluster]

        ax2.scatter(
            cluster_data["Age"],
            cluster_data["Income($)"],
            label=f"Cluster {cluster}"
        )

    if scale_data:
        centers = scaler.inverse_transform(km.cluster_centers_)
    else:
        centers = km.cluster_centers_

    ax2.scatter(
        centers[:, 0],
        centers[:, 1],
        marker="*",
        s=250,
        label="Centroids"
    )

    ax2.set_xlabel("Age")
    ax2.set_ylabel("Income ($)")
    ax2.legend()

    st.pyplot(fig2)

    st.subheader("Cluster Centers")

    center_df = pd.DataFrame(
        centers,
        columns=["Age", "Income ($)"]
    )

    st.dataframe(center_df)

    st.subheader("Elbow Method")

    sse = []

    k_range = range(1, 11)

    for k in k_range:
        model = KMeans(
            n_clusters=k,
            random_state=42,
            n_init=10
        )
        model.fit(data)
        sse.append(model.inertia_)

    fig3, ax3 = plt.subplots()

    ax3.plot(k_range, sse, marker="o")
    ax3.set_xlabel("Number of Clusters (K)")
    ax3.set_ylabel("SSE")
    ax3.set_title("Elbow Method")

    st.pyplot(fig3)

    st.subheader("Final Dataset")

    st.dataframe(df)

else:
    st.info("Please upload income.csv to begin.")